author:
  name: Matt Phillips
  picture: assets/img/profile.jpg

# site description
description: Thoughts on Software

# site url
url: http://mattphillips.io

# site title
title: Matt Phillips

# site version
version: 0.0.1

# contact
github_username: mattphillips
twitter_username: mattphillipsio
facebook_username: sirfilllips
linkedin_username: mhphillips

highlighter: pygments
