author:
  name: Matt Phillips
  picture: assets/img/profile.jpg
  bio: Software engineer sharing his thoughts on code ...

colours:
    primary: "#48CAC2"
    secondary: "#FF4081"
    primaryLight: "#A5EFEA"
# site description
description: Thoughts on Software

# site url
url: http://mattphillips.io

# site shortname
shortname: mattphillips

# site title
title: Matt Phillips

include: [".well-known"]

# site version
version: 0.0.1

# contact
github_username: mattphillips
twitter_username: mattphillipsio
linkedin_username: mhphillips

excerpt_separator: <!--excerpt_separator-->
